name: Code Review Check

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  check-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count lines in files
        run: |
          exceeded_lines=$(find . -type f -name "*" -exec awk 'END { if (NR > 250) print FILENAME }' {} \;)
          echo "$exceeded_lines" > exceeded_files.txt      
      - name: Send email notification
        if: failure()
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          FROM_EMAIL="shahaji@8848digital.com"
          TO_EMAIL="kshahaji04@gmail.com, kshahaji02@gmail.com"
          SUBJECT="Code Size Check Failed"
          BODY="The code changes exceed 250 lines. Please review!"
          
          curl -X "POST" "https://api.sendgrid.com/v3/mail/send" \
               -H "Authorization: Bearer $SENDGRID_API_KEY" \
               -H "Content-Type: application/json" \
               -d $'{
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "'"$TO_EMAIL"'"
                    }
                  ],
                  "subject": "'"$SUBJECT"'"
                }
              ],
              "from": {
                "email": "'"$FROM_EMAIL"'"
              },
              "content": [
                {
                  "type": "text/plain",
                  "value": "'"$BODY"'"
                }
              ]
            }'
          echo "Sending email notification about code size failure"
